//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyWorkingHour
    {
        public CompanyWorkingHour()
        {
            this.EmployeeDetailsTables = new HashSet<EmployeeDetailsTable>();
        }
    
        public int CompanyWorkingHourId { get; set; }
        public string ShiftName { get; set; }
        public string WorkingHours { get; set; }
        public string LunchTime { get; set; }
    
        public virtual ICollection<EmployeeDetailsTable> EmployeeDetailsTables { get; set; }
    }
}
