//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsTable
    {
        public EmployeeDetailsTable()
        {
            this.LoginTables = new HashSet<LoginTable>();
        }
    
        public int S_no { get; set; }
        public string EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int DesignationId { get; set; }
        public int EmployeeWorkingHours { get; set; }
        public Nullable<int> LeaveRequests { get; set; }
    
        public virtual CompanyWorkingHour CompanyWorkingHour { get; set; }
        public virtual EmployeeDesignationTable EmployeeDesignationTable { get; set; }
        public virtual RequestLeave RequestLeave { get; set; }
        public virtual ICollection<LoginTable> LoginTables { get; set; }
    }
}
