//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeManagementDBEntities : DbContext
    {
        public EmployeeManagementDBEntities()
            : base("name=EmployeeManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompanyWorkingHour> CompanyWorkingHours { get; set; }
        public DbSet<EmployeeDesignationTable> EmployeeDesignationTables { get; set; }
        public DbSet<EmployeeDetailsTable> EmployeeDetailsTables { get; set; }
        public DbSet<LoginTable> LoginTables { get; set; }
        public DbSet<PaymentRule> PaymentRules { get; set; }
        public DbSet<RequestLeave> RequestLeaves { get; set; }
    }
}
