//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLeave
    {
        public RequestLeave()
        {
            this.EmployeeDetailsTables = new HashSet<EmployeeDetailsTable>();
        }
    
        public int LeaveId { get; set; }
        public string LeaveType { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public string LeaveReason { get; set; }
    
        public virtual ICollection<EmployeeDetailsTable> EmployeeDetailsTables { get; set; }
    }
}
